.git
.github
.vscode

support_data
results
databases
uploads
__pycache__
static/js/node_modules
static/js/src/node_modules

**/__pycache__
**/*.pyc
**/.DS_Store
**/._*
**/.pytest_cache

*.tar
*.tar.gz
*.zip
